name: ci

on: [push, pull_request]

jobs:
  ci:
    name: continous integration
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'noryvn:')
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm

      - name: install dependency
        run: npm ci

      - name: typechecking
        run: npm run check

      - name: lint
        run: npm run lint
